[build]
  publish = "dist"
  command = "yarn build"

[context.production.environment]
  APP_ENV = "production"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "14.17.6"
