[build.environment]
  NODE_VERSION = "18.20.5"

[build]
  publish = "dist"
  command = "yarn build"

[context.production.environment]
  APP_ENV = "production"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200


